version: '3.5'
services:
  db:
    container_name: backoffice.mysql
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - ./.docker/mysql/schemas:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - my_networks
  redis:
    container_name: 'redis'
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=a4337bc45a8fc544c03f52dc550cd6e1e87021bc896588bd79e901e2
    ports:
      - "6379:6379"
networks:
  my_networks:
    name: my_networks
