-- MySQL Script generated by MySQL Workbench
-- sex 04 set 2022 15:16:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema backoffice_jobs
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `shorturl` ;

-- -----------------------------------------------------
-- Schema backoffice_jobs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shorturl` /*!40100 DEFAULT CHARACTER SET utf8 */;
